/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package array-0.5.0.0 */
#define VERSION_array "0.5.0.0"
#define MIN_VERSION_array(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 0)

/* package base-4.7.0.1 */
#define VERSION_base "4.7.0.1"
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  7 || \
  (major1) == 4 && (major2) == 7 && (minor) <= 0)

/* package blaze-builder-0.3.3.4 */
#define VERSION_blaze_builder "0.3.3.4"
#define MIN_VERSION_blaze_builder(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 3)

/* package bytestring-0.10.4.1 */
#define VERSION_bytestring "0.10.4.1"
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 4)

/* package directory-1.2.1.0 */
#define VERSION_directory "1.2.1.0"
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 1)

/* package network-2.6.0.2 */
#define VERSION_network "2.6.0.2"
#define MIN_VERSION_network(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  6 || \
  (major1) == 2 && (major2) == 6 && (minor) <= 0)

/* package process-1.2.1.0 */
#define VERSION_process "1.2.1.0"
#define MIN_VERSION_process(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 1)

/* package random-1.1 */
#define VERSION_random "1.1"
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)

/* package stm-2.4.4 */
#define VERSION_stm "2.4.4"
#define MIN_VERSION_stm(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  4 || \
  (major1) == 2 && (major2) == 4 && (minor) <= 4)

/* package text-1.2.0.4 */
#define VERSION_text "1.2.0.4"
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 0)

/* package transformers-0.4.2.0 */
#define VERSION_transformers "0.4.2.0"
#define MIN_VERSION_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 2)

/* package unix-2.7.1.0 */
#define VERSION_unix "2.7.1.0"
#define MIN_VERSION_unix(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  7 || \
  (major1) == 2 && (major2) == 7 && (minor) <= 1)

/* package zlib-0.5.4.2 */
#define VERSION_zlib "0.5.4.2"
#define MIN_VERSION_zlib(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 4)

/* tool alex-3.1.3 */
#define TOOL_VERSION_alex "3.1.3"
#define MIN_TOOL_VERSION_alex(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  1 || \
  (major1) == 3 && (major2) == 1 && (minor) <= 3)

/* tool cpphs-1.18.6 */
#define TOOL_VERSION_cpphs "1.18.6"
#define MIN_TOOL_VERSION_cpphs(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  18 || \
  (major1) == 1 && (major2) == 18 && (minor) <= 6)

/* tool gcc-4.8 */
#define TOOL_VERSION_gcc "4.8"
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  8 || \
  (major1) == 4 && (major2) == 8 && (minor) <= 0)

/* tool ghc-7.8.3 */
#define TOOL_VERSION_ghc "7.8.3"
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  7 || \
  (major1) == 7 && (major2) <  8 || \
  (major1) == 7 && (major2) == 8 && (minor) <= 3)

/* tool ghc-pkg-7.8.3 */
#define TOOL_VERSION_ghc_pkg "7.8.3"
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  7 || \
  (major1) == 7 && (major2) <  8 || \
  (major1) == 7 && (major2) == 8 && (minor) <= 3)

/* tool haddock-2.14.3 */
#define TOOL_VERSION_haddock "2.14.3"
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  14 || \
  (major1) == 2 && (major2) == 14 && (minor) <= 3)

/* tool happy-1.19.4 */
#define TOOL_VERSION_happy "1.19.4"
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  19 || \
  (major1) == 1 && (major2) == 19 && (minor) <= 4)

/* tool hpc-0.67 */
#define TOOL_VERSION_hpc "0.67"
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)

/* tool hsc2hs-0.67 */
#define TOOL_VERSION_hsc2hs "0.67"
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)

/* tool pkg-config-0.26 */
#define TOOL_VERSION_pkg_config "0.26"
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  26 || \
  (major1) == 0 && (major2) == 26 && (minor) <= 0)

